---
title: "Creating and working with vectors"
author: "Kiran Favre"
date: "2022-08-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(palmerpenguins)
```

## Let's make some vectors!

```{r}
marmot <- c("blue", "green", 4, "yellow")

# Check class of this vector
class(marmot)
```

Using c() will create a vector

```{r}
pika <- c(12.4, 6.8, 2, 4.9, 5.4)

#---------##---- multiply by a scalar

5.2 * pika  # this is not storing a value, just calculating

scalar_pika <- 5.2 * pika

scalar_pika

```


```{r}
bananas <- c(1, 2, 3)  
apples <- c(6, 7, 8)

bananas + apples  #vector addition
bananas - apples   # vector subtraction
bananas %*% apples  #vector mult via dot product

```


### Matrices 
```{r}
my_values <- seq( from = 1, to = 10)

my_matrix <- matrix(data =my_values, nrow= 2, ncol = 5, byrow = TRUE)
my_matrix

5 * my_matrix
class(my_matrix)  #can do this in console to see the class type, use in console
```

